// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXuDGD90WVzbfFjqkNnbsa3FFqMgywfBs',
    appId: '1:776142033777:web:e84e8195e8184707069cd0',
    messagingSenderId: '776142033777',
    projectId: 'todo-f8955',
    authDomain: 'todo-f8955.firebaseapp.com',
    storageBucket: 'todo-f8955.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGUHv6REeciEbXMrA6wl0ZjbHjE600z2s',
    appId: '1:776142033777:android:c0025db624b9997c069cd0',
    messagingSenderId: '776142033777',
    projectId: 'todo-f8955',
    storageBucket: 'todo-f8955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZagbDH_bIEK049j3BRQwv-fMgbBgJTdI',
    appId: '1:776142033777:ios:c4cec26eb23e06d6069cd0',
    messagingSenderId: '776142033777',
    projectId: 'todo-f8955',
    storageBucket: 'todo-f8955.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZagbDH_bIEK049j3BRQwv-fMgbBgJTdI',
    appId: '1:776142033777:ios:c4cec26eb23e06d6069cd0',
    messagingSenderId: '776142033777',
    projectId: 'todo-f8955',
    storageBucket: 'todo-f8955.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXuDGD90WVzbfFjqkNnbsa3FFqMgywfBs',
    appId: '1:776142033777:web:ed518beff5a0cf51069cd0',
    messagingSenderId: '776142033777',
    projectId: 'todo-f8955',
    authDomain: 'todo-f8955.firebaseapp.com',
    storageBucket: 'todo-f8955.firebasestorage.app',
  );
}
